baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Plugin Host'
primary: true
siteGroup: ff3de430-5176-4ff5-8dbb-5f68ca0cffa6 # Craft Plugin Host
sortOrder: 1
