enableVersioning: true
handle: locations
name: Locations
propagationMethod: all
siteSettings:
  0139fe08-9bdc-4427-b14d-4a332513e3df: # Craft Plugin Host
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry
    uriFormat: 'locations/{slug}'
type: channel
