enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  0139fe08-9bdc-4427-b14d-4a332513e3df: # Craft Plugin Host
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
