enableVersioning: true
handle: teamMembers
name: 'Team Members'
propagationMethod: all
siteSettings:
  0139fe08-9bdc-4427-b14d-4a332513e3df: # Craft Plugin Host
    enabledByDefault: true
    hasUrls: true
    template: team-members/_entry
    uriFormat: 'team-members/{slug}'
type: channel
